<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <StartupObject>Mystrose.App</StartupObject>
    <ApplicationIcon>Resources\Graphics\Mystrose.ico</ApplicationIcon>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Title>Mystrose</Title>
    <Authors>GentleGanku</Authors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
    <NoWarn>1701;1702</NoWarn>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702</NoWarn>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup>
	<Obfuscate>true</Obfuscate>
	<PlatformTarget>x64</PlatformTarget>
	<ErrorReport>none</ErrorReport>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Fonts\Albertus\AlbertusMTStd-Italic.ttf" />
    <None Remove="Resources\Fonts\Albertus\AlbertusMTStd-Light.ttf" />
    <None Remove="Resources\Fonts\Albertus\AlbertusMTStd.ttf" />
    <None Remove="Resources\Fonts\HypatiaSans\HypatiaSansPro-Black.ttf" />
    <None Remove="Resources\Fonts\HypatiaSans\HypatiaSansPro-Bold.ttf" />
    <None Remove="Resources\Fonts\HypatiaSans\HypatiaSansPro-ExtraLight.ttf" />
    <None Remove="Resources\Fonts\HypatiaSans\HypatiaSansPro-Light.ttf" />
    <None Remove="Resources\Fonts\HypatiaSans\HypatiaSansPro-Regular.ttf" />
    <None Remove="Resources\Fonts\HypatiaSans\HypatiaSansPro-Semibold.ttf" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Graphics\Mystrose.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Confuser.MSBuild" Version="1.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Costura.Fody" Version="5.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Fody" Version="6.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Macross.Json.Extensions" Version="3.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
    <PackageReference Include="WPF-UI" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Mystrose.crproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AxInterop.ShockwaveFlashObjects">
      <HintPath>..\..\Warthorn\C# - Main\Warthorn\bin\Release\net7.0-windows10.0.17763.0\AxInterop.ShockwaveFlashObjects.dll</HintPath>
    </Reference>
    <Reference Include="Interop.ShockwaveFlashObjects">
      <HintPath>..\..\Warthorn\C# - Main\Warthorn\bin\Release\net7.0-windows10.0.17763.0\Interop.ShockwaveFlashObjects.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Albertus\AlbertusMTStd-Italic.ttf" />
    <Resource Include="Resources\Fonts\Albertus\AlbertusMTStd-Light.ttf" />
    <Resource Include="Resources\Fonts\Albertus\AlbertusMTStd.ttf" />
    <Resource Include="Resources\Fonts\HypatiaSans\HypatiaSansPro-Black.ttf" />
    <Resource Include="Resources\Fonts\HypatiaSans\HypatiaSansPro-Bold.ttf" />
    <Resource Include="Resources\Fonts\HypatiaSans\HypatiaSansPro-ExtraLight.ttf" />
    <Resource Include="Resources\Fonts\HypatiaSans\HypatiaSansPro-Light.ttf" />
    <Resource Include="Resources\Fonts\HypatiaSans\HypatiaSansPro-Regular.ttf" />
    <Resource Include="Resources\Fonts\HypatiaSans\HypatiaSansPro-Semibold.ttf" />
    <Resource Include="Resources\Graphics\Mystrose.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Panels\General\FrozenPanel.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Core\ScriptMachine\Panels\Controls\ScriptCodelineItem.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
